#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SURTEX")]
	public partial class Surtex_BddDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCargos(Cargos instance);
    partial void UpdateCargos(Cargos instance);
    partial void DeleteCargos(Cargos instance);
    partial void InsertProductos(Productos instance);
    partial void UpdateProductos(Productos instance);
    partial void DeleteProductos(Productos instance);
    partial void InsertDepartamento(Departamento instance);
    partial void UpdateDepartamento(Departamento instance);
    partial void DeleteDepartamento(Departamento instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    #endregion
		
		public Surtex_BddDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.SURTEXConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Surtex_BddDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Surtex_BddDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Surtex_BddDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Surtex_BddDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cargos> Cargos
		{
			get
			{
				return this.GetTable<Cargos>();
			}
		}
		
		public System.Data.Linq.Table<Productos> Productos
		{
			get
			{
				return this.GetTable<Productos>();
			}
		}
		
		public System.Data.Linq.Table<Datos_Empresa> Datos_Empresa
		{
			get
			{
				return this.GetTable<Datos_Empresa>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamento
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insert_empleado")]
		public int Insert_empleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre_empleado", DbType="VarChar(50)")] string nombre_empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido_empleado", DbType="VarChar(50)")] string apellido_empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_empleado", DbType="VarChar(50)")] string cedula_empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_car, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_dep)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_empleado, apellido_empleado, cedula_empleado, id_car, id_dep);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Edit_empleado")]
		public int Edit_empleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_empleado", DbType="Int")] System.Nullable<int> id_empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre_empleado", DbType="VarChar(1)")] string nombre_empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido_empleado", DbType="VarChar(1)")] string apellido_empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_empleado", DbType="Int")] System.Nullable<int> cedula_empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_car, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_dep)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_empleado, nombre_empleado, apellido_empleado, cedula_empleado, id_car, id_dep);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Buscar_empleado")]
		public ISingleResult<Buscar_empleadoResult> Buscar_empleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_empleado", DbType="VarChar(50)")] string cedula_empleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_empleado);
			return ((ISingleResult<Buscar_empleadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Eliminar_empleado")]
		public int Eliminar_empleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_empleado", DbType="VarChar(50)")] string cedula_empleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_empleado);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cargos")]
	public partial class Cargos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_car;
		
		private string _nom_car;
		
		private EntitySet<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_carChanging(int value);
    partial void Onid_carChanged();
    partial void Onnom_carChanging(string value);
    partial void Onnom_carChanged();
    #endregion
		
		public Cargos()
		{
			this._Empleado = new EntitySet<Empleado>(new Action<Empleado>(this.attach_Empleado), new Action<Empleado>(this.detach_Empleado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_car", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_car
		{
			get
			{
				return this._id_car;
			}
			set
			{
				if ((this._id_car != value))
				{
					this.Onid_carChanging(value);
					this.SendPropertyChanging();
					this._id_car = value;
					this.SendPropertyChanged("id_car");
					this.Onid_carChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_car", DbType="VarChar(50)")]
		public string nom_car
		{
			get
			{
				return this._nom_car;
			}
			set
			{
				if ((this._nom_car != value))
				{
					this.Onnom_carChanging(value);
					this.SendPropertyChanging();
					this._nom_car = value;
					this.SendPropertyChanged("nom_car");
					this.Onnom_carChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cargos_Empleado", Storage="_Empleado", ThisKey="id_car", OtherKey="id_car")]
		public EntitySet<Empleado> Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				this._Empleado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Cargos = this;
		}
		
		private void detach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Cargos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Productos")]
	public partial class Productos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pro;
		
		private string _nom_pro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_proChanging(int value);
    partial void Onid_proChanged();
    partial void Onnom_proChanging(string value);
    partial void Onnom_proChanged();
    #endregion
		
		public Productos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pro
		{
			get
			{
				return this._id_pro;
			}
			set
			{
				if ((this._id_pro != value))
				{
					this.Onid_proChanging(value);
					this.SendPropertyChanging();
					this._id_pro = value;
					this.SendPropertyChanged("id_pro");
					this.Onid_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_pro", DbType="VarChar(50)")]
		public string nom_pro
		{
			get
			{
				return this._nom_pro;
			}
			set
			{
				if ((this._nom_pro != value))
				{
					this.Onnom_proChanging(value);
					this.SendPropertyChanging();
					this._nom_pro = value;
					this.SendPropertyChanged("nom_pro");
					this.Onnom_proChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Datos_Empresa")]
	public partial class Datos_Empresa
	{
		
		private string _nom_emp;
		
		private string _dir_emp;
		
		private string _tel_emp;
		
		public Datos_Empresa()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_emp", DbType="VarChar(50)")]
		public string nom_emp
		{
			get
			{
				return this._nom_emp;
			}
			set
			{
				if ((this._nom_emp != value))
				{
					this._nom_emp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dir_emp", DbType="VarChar(50)")]
		public string dir_emp
		{
			get
			{
				return this._dir_emp;
			}
			set
			{
				if ((this._dir_emp != value))
				{
					this._dir_emp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel_emp", DbType="VarChar(50)")]
		public string tel_emp
		{
			get
			{
				return this._tel_emp;
			}
			set
			{
				if ((this._tel_emp != value))
				{
					this._tel_emp = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dep;
		
		private string _nom_dep;
		
		private EntitySet<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_depChanging(int value);
    partial void Onid_depChanged();
    partial void Onnom_depChanging(string value);
    partial void Onnom_depChanged();
    #endregion
		
		public Departamento()
		{
			this._Empleado = new EntitySet<Empleado>(new Action<Empleado>(this.attach_Empleado), new Action<Empleado>(this.detach_Empleado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dep", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dep
		{
			get
			{
				return this._id_dep;
			}
			set
			{
				if ((this._id_dep != value))
				{
					this.Onid_depChanging(value);
					this.SendPropertyChanging();
					this._id_dep = value;
					this.SendPropertyChanged("id_dep");
					this.Onid_depChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_dep", DbType="VarChar(50)")]
		public string nom_dep
		{
			get
			{
				return this._nom_dep;
			}
			set
			{
				if ((this._nom_dep != value))
				{
					this.Onnom_depChanging(value);
					this.SendPropertyChanging();
					this._nom_dep = value;
					this.SendPropertyChanged("nom_dep");
					this.Onnom_depChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Empleado", Storage="_Empleado", ThisKey="id_dep", OtherKey="id_dep")]
		public EntitySet<Empleado> Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				this._Empleado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = this;
		}
		
		private void detach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_empleado;
		
		private string _Nombre_empleado;
		
		private string _Apellido_empleado;
		
		private string _Cedula_empleado;
		
		private System.Nullable<int> _id_car;
		
		private System.Nullable<int> _id_dep;
		
		private EntityRef<Cargos> _Cargos;
		
		private EntityRef<Departamento> _Departamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_empleadoChanging(int value);
    partial void OnId_empleadoChanged();
    partial void OnNombre_empleadoChanging(string value);
    partial void OnNombre_empleadoChanged();
    partial void OnApellido_empleadoChanging(string value);
    partial void OnApellido_empleadoChanged();
    partial void OnCedula_empleadoChanging(string value);
    partial void OnCedula_empleadoChanged();
    partial void Onid_carChanging(System.Nullable<int> value);
    partial void Onid_carChanged();
    partial void Onid_depChanging(System.Nullable<int> value);
    partial void Onid_depChanged();
    #endregion
		
		public Empleado()
		{
			this._Cargos = default(EntityRef<Cargos>);
			this._Departamento = default(EntityRef<Departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_empleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_empleado
		{
			get
			{
				return this._Id_empleado;
			}
			set
			{
				if ((this._Id_empleado != value))
				{
					this.OnId_empleadoChanging(value);
					this.SendPropertyChanging();
					this._Id_empleado = value;
					this.SendPropertyChanged("Id_empleado");
					this.OnId_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_empleado", DbType="VarChar(50)")]
		public string Nombre_empleado
		{
			get
			{
				return this._Nombre_empleado;
			}
			set
			{
				if ((this._Nombre_empleado != value))
				{
					this.OnNombre_empleadoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_empleado = value;
					this.SendPropertyChanged("Nombre_empleado");
					this.OnNombre_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido_empleado", DbType="VarChar(50)")]
		public string Apellido_empleado
		{
			get
			{
				return this._Apellido_empleado;
			}
			set
			{
				if ((this._Apellido_empleado != value))
				{
					this.OnApellido_empleadoChanging(value);
					this.SendPropertyChanging();
					this._Apellido_empleado = value;
					this.SendPropertyChanged("Apellido_empleado");
					this.OnApellido_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula_empleado", DbType="VarChar(50)")]
		public string Cedula_empleado
		{
			get
			{
				return this._Cedula_empleado;
			}
			set
			{
				if ((this._Cedula_empleado != value))
				{
					this.OnCedula_empleadoChanging(value);
					this.SendPropertyChanging();
					this._Cedula_empleado = value;
					this.SendPropertyChanged("Cedula_empleado");
					this.OnCedula_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_car", DbType="Int")]
		public System.Nullable<int> id_car
		{
			get
			{
				return this._id_car;
			}
			set
			{
				if ((this._id_car != value))
				{
					if (this._Cargos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_carChanging(value);
					this.SendPropertyChanging();
					this._id_car = value;
					this.SendPropertyChanged("id_car");
					this.Onid_carChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dep", DbType="Int")]
		public System.Nullable<int> id_dep
		{
			get
			{
				return this._id_dep;
			}
			set
			{
				if ((this._id_dep != value))
				{
					if (this._Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_depChanging(value);
					this.SendPropertyChanging();
					this._id_dep = value;
					this.SendPropertyChanged("id_dep");
					this.Onid_depChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cargos_Empleado", Storage="_Cargos", ThisKey="id_car", OtherKey="id_car", IsForeignKey=true)]
		public Cargos Cargos
		{
			get
			{
				return this._Cargos.Entity;
			}
			set
			{
				Cargos previousValue = this._Cargos.Entity;
				if (((previousValue != value) 
							|| (this._Cargos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cargos.Entity = null;
						previousValue.Empleado.Remove(this);
					}
					this._Cargos.Entity = value;
					if ((value != null))
					{
						value.Empleado.Add(this);
						this._id_car = value.id_car;
					}
					else
					{
						this._id_car = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cargos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Empleado", Storage="_Departamento", ThisKey="id_dep", OtherKey="id_dep", IsForeignKey=true)]
		public Departamento Departamento
		{
			get
			{
				return this._Departamento.Entity;
			}
			set
			{
				Departamento previousValue = this._Departamento.Entity;
				if (((previousValue != value) 
							|| (this._Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamento.Entity = null;
						previousValue.Empleado.Remove(this);
					}
					this._Departamento.Entity = value;
					if ((value != null))
					{
						value.Empleado.Add(this);
						this._id_dep = value.id_dep;
					}
					else
					{
						this._id_dep = default(Nullable<int>);
					}
					this.SendPropertyChanged("Departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Buscar_empleadoResult
	{
		
		private string _Apellido;
		
		private string _Nombre;
		
		private string _Cedula_empleado;
		
		private string _Cargo;
		
		private string _Departamento;
		
		public Buscar_empleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula_empleado", DbType="VarChar(50)")]
		public string Cedula_empleado
		{
			get
			{
				return this._Cedula_empleado;
			}
			set
			{
				if ((this._Cedula_empleado != value))
				{
					this._Cedula_empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(50)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="VarChar(50)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
